### ISSUE TITLE
Clicking tabs breaks UI

### ISSUE THREAD

**Issue by svenrademakers** [turing-machines/BMC-UI#10]
It is possible to completely break the UI by clicking on the tabs while an upgrade is in process. At some point the UI crashes. see:
![error](https://github.com/turing-machines/BMC-UI/assets/3875285/41b994ad-5ee2-410c-a3ce-1c237791c13e)

# Reproduction Scenario

* start a 'OS install' on the Node install tab
* while in progress click on other tabs

# Expected behavior

The node install is not affected. However, it would be nice to be able to return to the node install tab.
If this is not possible due to technical limitations, I at least expect not to be able to click other tabs while the current tab is 'in progress'

**Comment by svenrademakers** [comment]
@barrenechea do you have an idea on the complexity of this task :)?

**Comment by barrenechea** [comment]
Whoops, nice catch! Indeed, a quick patch would be blocking navigation if an ongoing BMC/Node flash is in progress, but I wonder if it's possible to make them a global event so the process is not disturbed when navigation changes occur.

Blocking navigation for that case would be [pretty easy](https://tanstack.com/router/v1/docs/framework/react/guide/navigation-blocking). Making it work on tab changes I'm not sure. I'll be playing with this during the weekend! I'll try to keep navigation alive 😄
