### ISSUE TITLE
add rounding to the fan control slider

### ISSUE THREAD

**Issue by svenrademakers** [turing-machines/BMC-UI#15]
found a minor issue with regards to the fan control slider:
![rounding](https://github.com/user-attachments/assets/53828995-2abe-4b97-b42b-402890183785)
as shown in the picture, the rendering is a bit wack when using the slider. Rounding with 2 decimals max is sufficient to solve the problem

**Comment by barrenechea** [comment]
That's subpar behavior 😄 I'll push a fix tomorrow!

Would it be worth having decimals there? I think it would be simpler to round it to the nearest integer... Decimals would be unneeded complexity for fan speed IMO

**Comment by svenrademakers** [comment]
i think intergers is more as fine, we only have a handful of cooling levels anyway in v2.5

**Comment by gjrtimmer** [comment]
> i think intergers is more as fine, we only have a handful of cooling levels anyway in v2.5

If there is only a limited amount of cooling levels available, should the slider then not only have those levels, meaning that the slider jumps between those levels or is it different for the main fan?

**Comment by barrenechea** [comment]
> > i think intergers is more as fine, we only have a handful of cooling levels anyway in v2.5
> 
> If there is only a limited amount of cooling levels available, should the slider then not only have those levels, meaning that the slider jumps between those levels or is it different for the main fan?

That's precisely how it works for me at least (2.4 board), is it different for 2.5? A gif would be helpful here 😄
