### ISSUE TITLE
Dockerization of the bmc-ui?

### ISSUE THREAD

**Issue by mcam10** [turing-machines/BMC-UI#2]
Hi, is there any plan to dockerize this repo at some point? 

The reason I ask is because:

1.  My bigger plan is to test the functionality of the firmware, tpi tool, ui, and flashing functionality using docker containers.. I thought id take a gander at the UI code and see if I could get it setup.

2.  Reproducible builds.. also help with testing etc etc..

I performed a` npm i && npm run dev`. Got the following errors:
```
npm ERR! code 1
npm ERR! path /Users/malikcameron/BMC-UI/node_modules/jpegoptim-bin
npm ERR! command failed
npm ERR! command sh -c node lib/install.js
npm ERR! compiling from source
npm ERR! Command failed: /Users/malikcameron/BMC-UI/node_modules/jpegoptim-bin/vendor/jpegoptim --version
npm ERR! dyld[15918]: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.9.dylib
npm ERR!   Referenced from: <D098E391-1E09-3994-B7C3-D9F78412A72E> /Users/malikcameron/BMC-UI/node_modules/jpegoptim-bin/vendor/jpegoptim
npm ERR!   Reason: tried: '/usr/local/opt/jpeg/lib/libjpeg.9.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/jpeg/lib/libjpeg.9.dylib' (no such file), '/usr/local/opt/jpeg/lib/libjpeg.9.dylib' (no such file), '/usr/local/lib/libjpeg.9.dylib' (no such file), '/usr/lib/libjpeg.9.dylib' (no such file, not in dyld cache)
npm ERR!
npm ERR!
npm ERR! jpegoptim pre-build test failed
npm ERR! Error: Command failed: /bin/sh -c ./configure --prefix="/Users/malikcameron/BMC-UI/node_modules/jpegoptim-bin/vendor" --bindir="/Users/malikcameron/BMC-UI/node_modules/jpegoptim-bin/vendor"
npm ERR!
npm ERR! checking build system type... x86_64-apple-darwin23.1.0
npm ERR! checking host system type... x86_64-apple-darwin23.1.0
npm ERR! checking for gcc... gcc
npm ERR! checking whether the C compiler works... yes
npm ERR! checking for C compiler default output file name... a.out
npm ERR! checking for suffix of executables...
npm ERR! checking whether we are cross compiling... no
npm ERR! checking for suffix of object files... o
npm ERR! checking whether we are using the GNU C compiler... yes
npm ERR! checking whether gcc accepts -g... yes
npm ERR! checking for gcc option to accept ISO C89... none needed
npm ERR! checking for a BSD-compatible install... /usr/bin/install -c
npm ERR! checking whether make sets $(MAKE)... yes
npm ERR! checking for jpeg_read_header in -ljpeg... no
npm ERR! Cannot find libjpeg or you have too old version (v6 or later required).
npm ERR!
npm ERR!     at /Users/malikcameron/BMC-UI/node_modules/bin-build/node_modules/execa/index.js:231:11
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at async Promise.all (index 0)

npm ERR! A complete log of this run can be found in: /Users/malikcameron/.npm/_logs/2023-11-18T21_49_14_099Z-debug-0.log
```
My host machine specs:
Sonoma OS 14.1 (23B74)
Using Intel Core i3
Node.js v20.4.0

I also tested on my MacOs Ventura 13.5.1 M2 chip.
Node.js v20.4.0.  

After some googling I had to install jpeg via brew. So a, `brew install jpeg`. After this got installed, the above worked. But this leads me to the point that it would probably help if this was dockerized so builds are reproducible..  let me know your thoughts on this one..

**Comment by svenrademakers** [comment]
This depends on community demands; there is no plan to dockerize this now. But we are open to suggestions. 
Also I'm happy to help out where needed to answer any technical questions you may have.

**Comment by gjrtimmer** [comment]
@mcam10 What could help if you were able to use the base of this PR of the bmc-firmware repository to create a `devcontainer` environment for this repository to facilitate easy development.

Please look at: https://github.com/turing-machines/BMC-Firmware/pull/230 hope this will inspire you, and if possible maybe a PR from you?

**Comment by barrenechea** [comment]
> [@mcam10](https://github.com/mcam10) What could help if you were able to use the base of this PR of the bmc-firmware repository to create a `devcontainer` environment for this repository to facilitate easy development.
> 
> Please look at: [turing-machines/BMC-Firmware#230](https://github.com/turing-machines/BMC-Firmware/pull/230) hope this will inspire you, and if possible maybe a PR from you?

Not sure if this would be needed anymore, the current codebase should run on any OS. No dependency is tied to a specific OS/runtime, other than using the Node version specified in `.nvmrc`. It was more related to how things used to be on bmc-ui v1.x.

Of course it could be added but _if_ the issue arises, otherwise it would over-complicate the development of bmc-ui (IMO).
